# Generated by Django 2.1 on 2019-05-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20190516_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='evaluation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
