# Generated by Django 2.1 on 2019-05-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20190518_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='click',
            field=models.IntegerField(default=0),
        ),
    ]
