# Generated by Django 2.1 on 2019-05-19 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_click'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todayclick', to='movie.Movie')),
            ],
        ),
    ]
