# Generated by Django 2.1 on 2019-05-19 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0008_todayclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluaton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='evaluation',
        ),
        migrations.AddField(
            model_name='evaluaton',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='evaluaton',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation', to=settings.AUTH_USER_MODEL),
        ),
    ]
