# Generated by Django 2.1 on 2019-05-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20190519_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaton',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluate', to='movie.Movie'),
        ),
    ]
