# Generated by Django 2.1 on 2019-05-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20190519_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaton',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
