# Generated by Django 2.1 on 2019-05-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_evaluaton_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaton',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
